theme: jekyll-theme-cayman
title: Chris Ruskai
description: Unity3D and C# app to learn more about both the Unity3D Engine and Newton’s Law of Physics by creating a virtual experiment using Newton’s Formula.
